// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface BannerTopComponent {
  Title?: string;
  Image?: { data: Media };
}
export interface BannerTopComponent_Plain {
  Title?: string;
  Image?: Media_Plain;
}

export interface BannerTopComponent_NoRelations {
  Title?: string;
  Image?: number;
}

