// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface CardComponent {
  LinkText?: string;
  Link?: string;
  Description?: string;
  Image?: { data: Media };
}
export interface CardComponent_Plain {
  LinkText?: string;
  Link?: string;
  Description?: string;
  Image?: Media_Plain;
}

export interface CardComponent_NoRelations {
  LinkText?: string;
  Link?: string;
  Description?: string;
  Image?: number;
}

