// Interface automatically generated by schemas-to-ts

import { CardComponent } from './CardComponent';
import { CardComponent_Plain } from './CardComponent';
import { CardComponent_NoRelations } from './CardComponent';

export interface CardZoneComponent {
  Cards: CardComponent[];
}
export interface CardZoneComponent_Plain {
  Cards: CardComponent_Plain[];
}

export interface CardZoneComponent_NoRelations {
  Cards: CardComponent_NoRelations[];
}

