// Interface automatically generated by schemas-to-ts

export interface ColumnTextComponent {
  Text1?: string;
  Text2?: string;
  Text3?: string;
  Text4?: string;
}
export interface ColumnTextComponent_Plain {
  Text1?: string;
  Text2?: string;
  Text3?: string;
  Text4?: string;
}

export interface ColumnTextComponent_NoRelations {
  Text1?: string;
  Text2?: string;
  Text3?: string;
  Text4?: string;
}

