// Interface automatically generated by schemas-to-ts

import { ColumnTextComponent } from './ColumnTextComponent';
import { ColumnTextComponent_Plain } from './ColumnTextComponent';
import { ColumnTextComponent_NoRelations } from './ColumnTextComponent';

export interface FooterComponent {
  Columns: ColumnTextComponent[];
}
export interface FooterComponent_Plain {
  Columns: ColumnTextComponent_Plain[];
}

export interface FooterComponent_NoRelations {
  Columns: ColumnTextComponent_NoRelations[];
}

