// Interface automatically generated by schemas-to-ts

export interface TextsRowComponent {
  TextLeft?: string;
  TextRight?: string;
}
export interface TextsRowComponent_Plain {
  TextLeft?: string;
  TextRight?: string;
}

export interface TextsRowComponent_NoRelations {
  TextLeft?: string;
  TextRight?: string;
}

